name: curt
description: Simple wrapper for curl in dart.
version: 0.0.3
repository: https://github.com/edufolly/curt

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  http: '>=0.13.5 <1.1.0'

dev_dependencies:
  # https://pub.dev/packages/coverage
  coverage: ^1.6.3

  # https://pub.dev/packages/lints
  lints: ^2.1.0

  # https://pub.dev/packages/markdown
  markdown: ^7.1.0

  # https://pub.dev/packages/test
  test: ^1.24.0
